### ISSUE TITLE
Multi Gateway assign

### ISSUE THREAD

**Issue by tobievii** [IoT-nxt/prototype#139]
Assign a gateway to multiple devices at once

**Comment by fluentart** [comment]
1) Select multiple devices in the device list
2) ???
3) Devices are all linked to a specific gateway.

We need to discuss step 2, and how we can reuse this in other cases, for instance applying a script/workflow or dashboard layout to many devices at once. 

I think adding a button next to remove called [MODIFY] when one or more devices are selected could work.

Then a panel opens that looks similar to when ADD DEVICE button is pressed.

This new panel would then allow you to choose what you'd like to apply to the selected devices:

[iotnxt plugin gateway]
[script]
[dashboard layout]

Anyone keen to mock this design up? Feedback/ideas?

**Comment by fluentart** [comment]
Same as https://github.com/IoT-nxt/prototype/issues/141

We need to code in this:

![Screenshot from 2019-06-14 14-24-25](https://user-images.githubusercontent.com/3116694/59509491-72ecfc00-8eb1-11e9-91c5-afc89b0622e1.png)

**Comment by mashaole** [comment]
https://github.com/IoT-nxt/prototype/pull/150/commits/9761cea911916a0983a28014ca9d3a3a16f0d7c2
