### ISSUE TITLE
Multiple device sharing

### ISSUE THREAD

**Issue by mashaole** [IoT-nxt/prototype#141]
**Is your feature request related to a problem? Please describe.**
Cornelis  wanted to share multiple devices but the functionality is not there

**Describe the solution you'd like**
the Modify button should also allow sharing device privately and publicly in addition to multiple gateway & workflow assigning

**Comment by fluentart** [comment]
We need to code in this:

![Screenshot from 2019-06-14 14-24-25](https://user-images.githubusercontent.com/3116694/59509441-52bd3d00-8eb1-11e9-8c32-36cec00e714b.png)

**Comment by mashaole** [comment]
https://github.com/IoT-nxt/prototype/pull/150/commits/81401f4e7bf68e6a237f98b87a40288ee7fbcbec
