### ISSUE TITLE
IoTnxt plugin - Nested arrays are not flattened 

### ISSUE THREAD

**Issue by fluentart** [IoT-nxt/prototype#153]
Report from TamWolff.

It seems the new iotnxt cluster plugin no longer flattens arrays in packet data for gateways. 

Fix and develop test so this regression would be detected next time.

**Comment by DeepaSoul** [comment]
@fluentart will you be handling this?

**Comment by fluentart** [comment]
Seems this issue was mis diagnosed. Not a bug only user error.
