### ISSUE TITLE
Device gateway changes for some reason

### ISSUE THREAD

**Issue by fluentart** [IoT-nxt/prototype#169]
**Describe the bug**
I picked up another device who’s gateway was changed. I’m not sure if I set it up incorrectly from the start, but I doubt it because I’ve been receiving data successfully until now.

**Comment by fluentart** [comment]
That is strange. Perhaps there is a bug where it changes the wrong device's gateway under some circumstances.

**Comment by mashaole** [comment]
was this on dev or production

**Comment by fluentart** [comment]
Production

**Comment by fluentart** [comment]
I think on a device it would be useful to see a history of changes.. 
```
date-time   username   changed gateway from aaaaaa to bbbbb
date-time   username   deleted dashboard widget graph 
```

**Comment by fluentart** [comment]
We've received reports that something similar is happening with workflow scripts as well.

**Comment by VincentKgadima** [comment]
A device history feature has been added to see which user/account has made changes to a specific device. If a gateway changes again, navigate to the device and click this button 
![image](https://user-images.githubusercontent.com/46519338/61536035-ff03bd80-aa33-11e9-9829-ddbd3dc5c169.png)to see which account has changed it. This issue will be marked as closed.
