### ISSUE TITLE
Can't change gateways

### ISSUE THREAD

**Issue by vaneedencc** [IoT-nxt/prototype#181]
**Describe the bug**
Can't change gateway option for new TELTONIKA devices.

**To Reproduce**
Go to a TELTONIKA devices with the name in caps and try and change gateway option.

**Expected behavior**
The gateway should be able to clear or change.

**Screenshots**
![image](https://user-images.githubusercontent.com/52816799/61884212-20651d80-aefc-11e9-9f3d-ebc5a66f0945.png)
![image](https://user-images.githubusercontent.com/52816799/61884369-67531300-aefc-11e9-985f-e39a3ef9d227.png)
![image](https://user-images.githubusercontent.com/52816799/61884401-73d76b80-aefc-11e9-871f-4faf1c7faa58.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser : Chrome
 - Version : 75.0.3770.142

**Comment by fluentart** [comment]
Is this device on your account?

**Comment by vaneedencc** [comment]
No, it's on raymond's account. But logged in with his user I also can't change it.

**Comment by fluentart** [comment]
fixed in https://github.com/IoT-nxt/prototype/commit/2d89fe1507cecddbfefcafca69b98977b18e08f7
