### ISSUE TITLE
Prototyper not loading nor can any device on API or MQTT connect 

### ISSUE THREAD

**Issue by tobievii** [IoT-nxt/prototype#190]
https://prototype.iotnxt.io/

**Comment by tobievii** [comment]
https://cdn.discordapp.com/attachments/562167091055296522/623167785173778432/unknown.png

**Comment by rvdende** [comment]
This is not the platform for server devops related issues.

**Comment by rvdende** [comment]
Tobie,

Github is not the correct platform for server specific issues. Github issues is for reporting code bugs/feature requests.

For https://prototype.iotnxt.io/ server instance issues please mail devops and cc me.

I'm aware of performance issues related to the 5.0.x range of prototype installs, of which prototype.iotnxt.io has the most load, thus I am not surprised the server is now unresponsive.

As stated on discord I can not even ssh into the box, and I do not have permission to reset it using the devops azure tools.

For mission critical devices please make sure to run your own isolated instance of prototype.

I am making progress on fixing the performance issues, I've had to dig through and refactor months of code. Apologies, but it is for the better. Feel free to test 5.1.x on https://8bo.org/ which is my personal test server. Also not for production use ofcourse!

5.1.x currently does not have iotnxt queue connectivity in yet and that part is being worked on right now.

More specifically I've been working on restructuring the core system of prototype so it can handle more devices and more data with the limited resources I have available. (A single cloud instance is running prototype.iotnxt.io)

I hope this provides clarity on the situation regarding the server issue.



Kind Regards,

Rouan van der Ende
Software Developer

[cid:iotnxt_923a479a-3b3a-4b43-ab9c-c7272a30fd3f.png]<https://www.iotnxt.com/>


Address: Bylsbridge Office Park, Building 14, Block C, 1st Floor, Alexandra Road, Highveld Ext 73, Centurion, Gauteng, 0046, South Africa
Phone: +27 12 880 0114
Mobile: +27 62 933 1183
Email: rouan.vanderende@iotnxt.com<mailto:rouan.vanderende@iotnxt.com>
Website: https://www.iotnxt.com

[cid:facebook_7fa50cc5-bd2e-456e-b71e-bcc6975537f7.png]<https://www.facebook.com/iotnxt/> [cid:linkedin_de143d75-2ff5-460f-b904-2d40ec2e8b51.png] <https://www.linkedin.com/company/iot.nxt>  [cid:twitter_84ab30d9-fec7-4e63-bb5e-8291caf481e8.png] <https://twitter.com/iot_nxt>  [cid:youtube_7ef73685-9dd4-488f-8407-84b0638dac87.png] <https://www.youtube.com/channel/UC_T4pl8fw5xijduERcOtTzQ>  [cid:Location-Icon_68f5d1d7-c4ad-447e-8890-cfc8f35cf158.png] <https://bit.ly/2vzWxgi>


[cid:E-mail-signature_67434c31-c307-40f1-9b37-adec7ea86304.png]

Disclaimer and Confidentiality Notice: IoT.nxt
The information contained in this e-mail communication is confidential. This information is intended solely for the use of the intended recipient named above. If you have received this e-mail communication in error, please notify the sender  rouan.vanderende@iotnxt.com<mailto:rouan.vanderende@iotnxt.com?subject=Disclaimer%20error,%20email%20received%20by%20mistake>  immediately by e-mail if you have received this e-mail by mistake and delete this e-mail from your system. In the event that you are not the intended recipient, you are hereby notified that any disclosure, distribution, use of, printing, copying or other action on the contents of this e-mail communication is strictly prohibited. This e-mail communication and its contents are not intended to be legally binding on IoT.nxt, its affiliates or the sender hereof nor should the contents hereof be construed to amend any contractual arrangement in place, unless explicitly stated herein. IoT.nxt accepts no liability for any loss or damage, whether direct, indirect, consequential or economic, however caused, which may result directly or indirectly from this e-mail communication or from any files attached hereto. Save for bona fide company matters, IoT.nxt does not accept any responsibility for any material, views or opinions contained in this email. This email is further subject to the provisions of the Protection of Personal Information Act 4 of 2013.



________________________________
