### ISSUE TITLE
Device share not showing up

### ISSUE THREAD

**Issue by tobievii** [IoT-nxt/prototype#202]
Hi, device sharing not showing up 

I click on share and share the device with user but user cannot see the device 

Running on current DEV branch 

T

**Comment by rvdende** [comment]
Yes this bug is known and was caused by the refactoring to solve the performance issues.
At the moment development is on hold by management.

PR will be accepted for this issue, and when I get a chance I'll see if I can resolve this.

**Comment by tobievii** [comment]
Thank you !

If I just have this , Im happy tnx, system works very well
