### ISSUE TITLE
Client build issues

### ISSUE THREAD

**Issue by branteforest** [IoT-nxt/prototype#203]
Hi There.

Struggling to build the client application. ~/prototype/client# npm install runs fine, but then issues with
**npm run build**
> prototype-client@5.1.0 build /root/prototype/client
> webpack --env prod --mode production
Webpack using prod
Hash: 2bf3a824df2c6a13721a
Version: webpack 4.41.4
Time: 120439ms
Built at: 12/26/2019 9:28:10 AM

Getting the following error, followed by loads more similar.
ERROR in ../server/shared/prototypews.ts
Module not found: Error: Can't resolve 'isomorphic-ws' in '/root/prototype/server/shared'
 @ ../server/shared/prototypews.ts 1:18-42
 @ ./src/api.ts
 @ ./src/index.tsx

Steps followed before:
Got many monaco editor errors, so installed to the following versions to resolve:
monaco-editor-webpack-plugin@1.7.0
monaco-editor@0.15.1
webpack 4.41.4

My environment:
Digital Oceran VM
Description:    Ubuntu 18.04.3 LTS
Release:        18.04
Codename:       bionic
Ubuntu 18.04.3 LTS (GNU/Linux 4.15.0-72-generic x86_64)
Node JS, I tried with node/8.16.2 and node/11.15.0 and node/13.0.1. Same error with each one

Using SSH from a mac to run terminal commands

Any ideas wil be very welcome. See attached
[terminal-log.txt](https://github.com/IoT-nxt/prototype/files/4002123/terminal-log.txt)
 complete terminal output

**Comment by rvdende** [comment]
Ah it seems the dependency 'isomorphic-ws is not yet installed in your node_modules. Both the server and client depend on this, and it is only listed as a dependency in the main server package.json.

So if you go up a folder and do `npm install` in the parent folder it should install this dependency. Then if you ran the commands as you did in /client it should find this dependency in the parent node_modules folder.

I hope this makes sense?

**Comment by branteforest** [comment]
Excellent @rvdende , works perfectly now. Thank you very much

**Comment by rvdende** [comment]
It's a pleasure @branteforest . 

Documentation has been fixed just now in https://github.com/IoT-nxt/prototype/commit/18f22e7517631f47fcce607fe9050d590574c159

Closing issue.
