### ISSUE TITLE
Multiple Queue publishing from Prototype 

### ISSUE THREAD

**Issue by DarrenWPragma** [IoT-nxt/prototype#47]
I have multiple devices that send messages to one virtual gateway, where each device send messages at their own interval and frequency. But it looks like the gateway sends all devices’ data even though only one device’s data was received. 

This causes our Database to get full really quickly because you'll have one device that sends data to the queue every few seconds, depending on the overall transmission frequency of all devices, even though data is in fact only sent every 10min for a specific device. 

Prototype should only publish data on the queue per device.

**Comment by fluentart** [comment]
Sounds like a bug in https://github.com/IoT-nxt/prototype/blob/dev/src/plugins/iotnxt/iotnxtserverside.ts#L501

**Comment by fluentart** [comment]
@mashaole has been briefed and is now working on resolving this issue.

**Comment by fluentart** [comment]
A workaround in the short term would be to add a new gateway for each device.

**Comment by DarrenWPragma** [comment]
Thanks for the workaround, but it’s going to take a long time to correct as I have 48 devices to fix and relink them up in Commander as well. 

Any idea how long this will take roughly?

**Comment by fluentart** [comment]
Right now I can't give you an estimated time.

**Comment by fluentart** [comment]
Bug has been fixed in https://github.com/IoT-nxt/prototype/commit/c2d58e3c74266f7bc06c91bfdcfce46105e15ee1
