### ISSUE TITLE
All devices dissappear after deleting a single device

### ISSUE THREAD

**Issue by fluentart** [IoT-nxt/prototype#52]
All devices dissappear after deleting a single device. I did this by selecting a single device with the tickmark, then clicking [DELETE] at the top of the list.

Only after a forced reload devices display correctly again.

**Comment by mashaole** [comment]
ill handle this while @DeepaSoul is busy with the ESP32

**Comment by mashaole** [comment]
https://github.com/IoT-nxt/prototype/commit/72962e56dbaf38f0642f9dd81fd93e483caadf31  ive just fixed this issue
