### ISSUE TITLE
All code missing

### ISSUE THREAD

**Issue by tobievii** [IoT-nxt/prototype#53]
Please restore the code for device https://prototype.iotnxt.io/u/tobie/view/teltonika_352093087587449 

All the code that was created is now missing in action. 

Sure you could find it in the mongodb

**Comment by fluentart** [comment]
When was the workflow code added?
I did notice that DB entries seem to have been rolled back in the past few days.
At the moment we do not store code edits, only the latest code per device.

So unless DevOps (Richard/Gert) can say what happened to the data I can not help to restore missing data.

**Comment by tobievii** [comment]
It was on there for the last 3 months ? OMG

**Comment by fluentart** [comment]
The database shows this device state was created (or recreated) 
"_created_on" : ISODate("2019-03-25T13:23:40.016Z"),

The device might have existed before this, but might have been deleted ? Any chance you could have cleared state or deleted the device?

**Comment by tobievii** [comment]
Not a chance, unless someone else deleted it . I'll redo code, maybe good to add some change control to prototyper so none other than owner can delete

**Comment by fluentart** [comment]
Yeah it is a good idea to add logging for device deletion and code changes. Pull requests are welcome.
