### ISSUE TITLE
login issue - fresh install , default credentials not working

### ISSUE THREAD

**Issue by tobievii** [IoT-nxt/prototype#54]
Done fresh pull on both dev and master, default logins not working

**Comment by fluentart** [comment]
Are you on windows? Apparently there's some additional steps for windows install.
Simpiwe can you assist here please

**Comment by DeepaSoul** [comment]
Are you able to load the main screen? only problem being the fact that the default logins don't work.

**Comment by Tobievi** [comment]
I'm on linux , main screen loads , as soon as you try and login with default logins it reverts back to the main screen with login again

**Comment by Tobievi** [comment]
> Are you able to load the main screen? only problem being the fact that the default logins don't work.

yes

**Comment by fluentart** [comment]
I've only seen that happen on old browsers.
Please use latest Chrome or Firefox until we can fix cross browser.

**Comment by Tobievi** [comment]
using chromium , will test now on firefox

**Comment by fluentart** [comment]
@mashaole login needs to report JSON response so people can see whats happening.
@Tobievi apologies, rapid codebase changes leads to breakages :)

**Comment by Tobievi** [comment]
perfect works from firefox and windows chrome remotely

**Comment by Tobievi** [comment]
@fluentart no probs thaks for the quick replies

**Comment by fluentart** [comment]
Strangeness. Marking this as a bug until we can figure out whats causing this. 
@VincentKgadima this is not closed.

**Comment by fluentart** [comment]
closing until this pops up again
