### ISSUE TITLE
HTTP plugin causing page to fail to load

### ISSUE THREAD

**Issue by fluentart** [IoT-nxt/prototype#58]
Process to replicate:

Create new account. 
Go to options > HTTP > create a GET endpoint.
Use another browser (possibly logged in to another account) not sure if cookies affect this, but it shouldn't. Open the new HTTP endpoint in browser.
Refresh home page.

Error is:
```
TypeError: Cannot read property 'gps' of null
```

**Comment by DeepaSoul** [comment]
Bug fix link: https://github.com/IoT-nxt/prototype/commit/aa82dd87ce93b5fd230c8071f00aa5ec07947894
