### ISSUE TITLE
Headers auth not dynamic

### ISSUE THREAD

**Issue by tobievii** [IoT-nxt/prototype#59]
![image](https://user-images.githubusercontent.com/5588288/56205223-7139c000-6049-11e9-99a1-710679687e03.png)

The base64 encoding needs to be added, as the user will use this and will find that it is not working

**Comment by fluentart** [comment]
That's already been base64'd whats the problem exactly?

**Comment by fluentart** [comment]
See https://github.com/IoT-nxt/prototype/blob/dev/client/components/apiInfo.jsx#L54

```js
    var authheader = 'Basic ' + Buffer.from("api:key-" + this.props.apikey).toString('base64')
```

```jsx
            <pre className="commanderBgPanel" style={{ fontSize: 12 }}>
              "Authorization":"{authheader}"<br />
              "Content-Type":"application/json"
            </pre>
```

**Comment by fluentart** [comment]
If anything the documentation wording can be improved so its more clear.

**Comment by tobievii** [comment]
Hi, 

I see it there , but then there is a bug, as the "key" you suggest does not work when adding it to a header. After some investigation , i took the api-key(all of the rest) and did my own encode64 and the Base "code" is different then the only suggested 

I

**Comment by tobievii** [comment]
It seems like it's taking another props.apikey and making that base64

**Comment by fluentart** [comment]
props.apikey is how react gets the currently logged in user's apikey to use on the page and it does more than just base64 it. It's api:key-xxxxxxxxxxxxxx  and base64's all of that. See the first video here: https://www.youtube.com/playlist?list=PLOAW9rdD5Gv8j4NJqDSfqN9F0dDSj3idh and follow along with postman. compare the header generated in postman to what is generated for you in prototype's interface. You will see it is exactly the same.

**Comment by tobievii** [comment]
The hosted version works fine, i cloned the repo and when log in with default user the generated header is different to the one you actually have to use. I did exactly that , copied the api:key-xxxxxxxxxxxxxx  and encoded to base64. as the one that is auto generated (see screenshot) is the one that did not work , response user not authenticated, then did the base64 and got the following Basic YXBpOmtleS0ydDEzeW5pbHE1aWlkZjEyNWh6ajV2cWltMmw1cmtoMw== on local machine, you can see it different to the one "recommended" ... No errors in F12. Hence my bug report. Can recreate it by cloning dev and fresh build .

**Comment by tobievii** [comment]
used https://www.base64decode.org/ , and getting data to the system perfectly with new code and not code in screenshot

**Comment by fluentart** [comment]
Not sure if bug or user error.

**Comment by tobievii** [comment]
Will do screen record.

**Comment by fluentart** [comment]
@tobievii is a screen recoding coming or can we close this issue?
