### ISSUE TITLE
Start at boot

### ISSUE THREAD

**Issue by branteforest** [IoT-nxt/prototype#60]
Hi. What is the best way to make this application run at boot. I have it installed and working in Ubuntu 18.04. I also installed Forever.

**Comment by branteforest** [comment]
Managed to get it working using systemd and creating a manual service

**Comment by fluentart** [comment]
Hi @branteforest thanks for commenting, nice to hear of people using this. We should definitely document how to set it up as a service.

**Comment by fluentart** [comment]
@branteforest this has been added to documentation in https://github.com/IoT-nxt/prototype/pull/91

**Comment by fluentart** [comment]
Direct link to documentation: https://github.com/IoT-nxt/prototype#setup-as-a-service
