### ISSUE TITLE
Load time too high

### ISSUE THREAD

**Issue by fluentart** [IoT-nxt/prototype#62]
I think we need to move to lazy-loading some components. Especially Monaco editor.

**Comment by fluentart** [comment]
Some documentation on how to do lazy loading: https://blog.logrocket.com/lazy-loading-components-in-react-16-6-6cea535c0b52

**Comment by DeepaSoul** [comment]
Fix Commit: https://github.com/IoT-nxt/prototype/pull/89/commits/2f66e5734dbb90d3ffd42f76f7a7c85e42025fc9
