### ISSUE TITLE
Application should not function until admin password is changed

### ISSUE THREAD

**Issue by mohag** [IoT-nxt/prototype#79]
**Is your feature request related to a problem? Please describe.**
The admin login works with the default (insecure) password, which means that the application can be used without changing the password, resulting in a huge security risk.

**Describe the solution you'd like**
If the administrator logs in with the default password, the web interface should only allow the password to be changed and enforce a different password.

**Describe alternatives you've considered**
Generating and saving a random password on first start, which needs to be retrieved from a file / logs on the server. (This is useful for a reset option, but will likely result in a useless instance if write permissions are denied to the save location or if logs are rotated too quickly)

**Additional context**
https://techcrunch.com/2018/10/05/california-passes-law-that-bans-default-passwords-in-connected-devices/

**Comment by fluentart** [comment]
@mohag this has now been implemented by @VincentKgadima
